# Generated by Django 5.1.6 on 2025-04-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FAVORITE', 'Favorite'), ('CANCEL', 'Cancel')], default='FAVORITE', max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_as_food', to='foodspots.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'food')},
            },
        ),
    ]
