# Generated by Django 5.1.6 on 2025-06-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
