# Generated by Django 5.1.6 on 2025-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0002_order_ordered_date_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='shipping_fee_per_km',
            field=models.IntegerField(default=2000),
        ),
    ]
