# Generated by Django 5.1.6 on 2025-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subcart',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
