# Generated by Django 5.1.6 on 2025-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0002_alter_user_options_remove_user_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
