# Generated by Django 5.1.6 on 2025-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0003_order_shipping_fee_restaurant_shipping_fee_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('RESTAURANT_USER', 'Restaurant User'), ('ADMIN', 'Admin')], default='', max_length=20),
        ),
    ]
