# Generated by Django 5.1.6 on 2025-04-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
