# Generated by Django 5.1.6 on 2025-05-24 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0006_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food_reviews', to='foodspots.orderdetail'),
        ),
        migrations.AlterField(
            model_name='foodreview',
            name='star',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='foodreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_food_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
