# Generated by Django 5.1.6 on 2025-06-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0007_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='image',
        ),
    ]
