# Generated by Django 5.1.6 on 2025-05-24 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0007_alter_foodreview_order_detail_alter_foodreview_star_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_food_reviews', to='foodspots.orderdetail'),
        ),
    ]
