# Generated by Django 5.1.6 on 2025-05-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspots', '0008_alter_foodreview_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprice',
            name='price',
            field=models.IntegerField(),
        ),
    ]
